image:
  repository: "gyorgy19/gateway-service"
  tag: "0.1.0"

serviceAccount:
  create: true
  name: "gateway-service"

service:
  type: ClusterIP
  port: 3000

podAnnotations:
  sidecar.opentelemetry.io/inject: "otel-resources/collector"
  instrumentation.opentelemetry.io/inject-nodejs: "otel-resources/instrumentation"

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: gateway-service.garnaudov.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: gateway-service-tls
      hosts:
        - gateway-service.garnaudov.com

env:
  - name: PORT
    value: "3000"
  - name: SERVICE_NAME
    value: "gateway-service"
  - name: MATCHMAKING_URL
    value: "http://matchmaking-service.arena-matchmaking-service.svc.cluster.local:3001"
  - name: GAMESTATE_URL
    value: "http://gamestate-service.arena-gamestate-service.svc.cluster.local:3002"
  - name: POLL_INTERVAL_MS
    value: "100"