image:
  repository: "gyorgy19/web-frontend"
  tag: "0.1.1"

serviceAccount:
  create: true
  name: "web-frontend"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arena.garnaudov.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: web-frontend-tls
      hosts:
        - arena.garnaudov.com

env:
  - name: PORT
    value: "8080"
  - name: SERVICE_NAME
    value: "web-frontend"
  - name: GATEWAY_URL
    value: "https://gateway-service.garnaudov.com"
  - name: GATEWAY_WS_URL
    value: "wss://gateway-service.garnaudov.com/ws"
