replicas: 1
ingress:
  enabled: true
  ingressClassName: "traefik"
  path: /
  pathType: Prefix
  hosts:
    - grafana.garnaudov.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.garnaudov.com

grafana.ini:
  server:
    domain: grafana.garnaudov.com
    root_url: https://grafana.garnaudov.com

persistence:
  enabled: true
  size: 5Gi
  storageClassName: local-path

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Metrics
        type: prometheus
        uid: mimir
        orgId: 1
        url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
        access: proxy
        isDefault: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "default"
      - name: Logs
        type: loki
        uid: loki
        orgId: 1
        url: http://loki-gateway.loki.svc.cluster.local
        access: proxy
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "default"
      - name: Logs Blog
        type: loki
        uid: loki-blog
        orgId: 1
        url: http://loki-gateway.loki.svc.cluster.local
        access: proxy
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "blog"
      - name: Logs Arena
        type: loki
        uid: loki-arena
        orgId: 1
        url: http://loki-gateway.loki.svc.cluster.local
        access: proxy
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "arena"
