replicas: 1
ingress:
  enabled: true
  ingressClassName: "traefik"
  path: /
  pathType: Prefix
  hosts:
    - grafana.garnaudov.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.garnaudov.com

grafana.ini:
  server:
    domain: grafana.garnaudov.com
    root_url: https://grafana.garnaudov.com

persistence:
  enabled: true
  size: 5Gi
  storageClassName: local-path

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090
        access: proxy
        isDefault: true
